quizId:
  in: path
  name: id
  description: The ID of the quiz.
  schema:
    type: string
  example: "42"
  required: true

questionId:
  in: path
  name: qid
  description: The ID of the question.
  schema:
    type: string
  example: "1337"
  required: true