list:
  get:
    tags:
      - Users
    summary: List all users.
    operationId: listUsers
    responses:
      '200':
        description: A list of all users.
        # TODO: pagination
        content:
          application/json:
            schema:
              users:
                type: array
                items:
                  $ref: 'schemas.yaml#/User'
            example:
              users:
                - id: "267"
                  email: foo@example.com
                  username: ayyy
                - id: "11"
                  email: hmmmm@example.com
                  username: hmmmmstve113
      '403':
        $ref: '../responses.yaml#/Unauthorized'
      '500':
        $ref: '../responses.yaml#/InternalServerError'
get:
  get:
    tags:
      - Users
    summary: Get information about a single user.
    operationId: getUser
    parameters:
      - in: path
        name: id
        description: The user's ID.
        schema:
          type: string
        example: "99"
        required: true
    responses:
      '200':
        description: OK.
        content:
          application/json:
            schema:
              $ref: '../auth/schemas.yaml#/User'
            example:
              id: "123"
              email: foo@example.com
              username: hmmmmstve113
      '403':
        $ref: '../responses.yaml#/Unauthorized'
      '500':
        $ref: '../responses.yaml#/InternalServerError'